.devcontainer.json, .editorconfig, .github/dependabot.yml, .github/workflows/lint.yaml, .yaml-lint.yml
- Update the devcontainer setting for develop with VSCode
- Linting on GitHub Actions
- Automatically update GitHub Actions by dependabot
=> Update setting files for development

.github/workflows/test.yaml, src/r-rig/devcontainer-feature.json, src/r-rig/install.sh, test/_global/r_quarto.sh, test/_global/scenarios.json, test/r-rig/test.sh
=> Adds install R (via rig) feature

.github/workflows/test.yaml, src/r-rig/install.sh
=> [r-rig] Install for non-root user

.github/workflows/test.yaml
Avoid running unnecessary tests
=> [CI] Tests only detected features and remove the push trigger

src/r-rig/devcontainer-feature.json, src/r-rig/install.sh, test/_global/scenarios.json
=> [r-lig] Add new option to install the rmarkdown R package

README.md, src/quarto-cli/NOTES.md, src/quarto-cli/devcontainer-feature.json, src/r-rig/NOTES.md, src/r-rig/devcontainer-feature.json
Move the documents to their own directories.
=> [quarto-cli][r-rig] Adds NOTES.md

src/quarto-cli/devcontainer-feature.json, src/quarto-cli/install.sh, test/quarto-cli/jupyter_quarto.sh, test/quarto-cli/scenarios.json, test/quarto-cli/tinytex.sh
The tinytex installation option was not working and will be corrected to work.
=> [quarto-cli] Fix to install tinytex

src/r-rig/devcontainer-feature.json, src/r-rig/install.sh, test/r-rig/rpackages-source-install.sh, test/r-rig/scenarios.json
Close #54
Note that this option uses the GitHub API.
That means it is limited by the rate limit.
=> [r-rig] Add a new option to install vscDebugger

src/r-rig/devcontainer-feature.json, src/r-rig/install.sh
=> [r-rig] Add missing python3-dev for sauce installation of pip packages

README.md
These features are now stable.
=> [Docs] Update README to reflect latest status

src/r-rig/devcontainer-feature.json, src/r-rig/install.sh, test/r-rig/rpackages-source-install.sh, test/r-rig/scenarios.json
=> [r-rig] Add a new option to install renv

src/r-apt/devcontainer-feature.json, src/r-apt/install.sh, test/r-apt/all-on-debian-stable.sh, test/r-apt/all-on-focal.sh, test/r-apt/all-on-jammy.sh, test/r-apt/all-on-not-testing.sh, test/r-apt/scenarios.json
=> [r-apt] Add a new option to install renv

.github/workflows/test.yaml, src/apt-packages/NOTES.md, src/apt-packages/devcontainer-feature.json, src/apt-packages/install.sh, test/apt-packages/install-curl-nano-wget.sh, test/apt-packages/install-curl-nano.sh, test/apt-packages/install-r-packages.sh, test/apt-packages/scenarios.json, test/apt-packages/test.sh
Add a Dev Container Feature to install arbitrary packages via apt.
This allows we to install apt packages without the need to write a Dockerfile.
=> New Feature: apt-packages

.github/workflows/validate.yml
Follow devcontainers/feature-starter#26
=> [CI] Add validation workflow for PRs

src/r-rig/devcontainer-feature.json, src/r-rig/install.sh
Delete the line that I forgot to delete in #125.
=> [r-rig] Should not install pak twice

src/quarto-cli/NOTES.md, src/quarto-cli/devcontainer-feature.json, src/quarto-cli/install.sh, test/quarto-cli/chromium-on-debian.sh, test/quarto-cli/scenarios.json
=> [quarto-cli] Add a new option `installChromium`

src/quarto-cli/devcontainer-feature.json, src/quarto-cli/install.sh
Fix an editing error in #133 and minor refactoring.
=> [quarto-cli] Remove unused line

.github/workflows/test.yaml, README.md, src/renv-cache/NOTES.md, src/renv-cache/devcontainer-feature.json, src/renv-cache/install.sh, test/renv-cache/gh-version-renv.sh, test/renv-cache/r-apt.sh, test/renv-cache/r-rig.sh, test/renv-cache/rocker-r-ver.sh, test/renv-cache/scenarios.json, test/renv-cache/test.sh
Close #139
~~A test should be added to verify that the cache is properly stored in place.~~
-> Done.
=> New Feature: renv-cache

src/renv-cache/NOTES.md
Change the NOTES as the directory will be always created by #142.
=> [renv-cache] Fix notes (System Requirements)

src/r-apt/devcontainer-feature.json, src/r-apt/install.sh, src/r-packages/devcontainer-feature.json, src/r-packages/install.sh, src/r-rig/devcontainer-feature.json, src/r-rig/install.sh
=> [r-apt][r-packages][r-rig] clean up pak's cache

src/quarto-cli/NOTES.md, src/quarto-cli/devcontainer-feature.json, src/quarto-cli/install.sh
=> [quarto-cli] Supports Quarto CLI arm64 deb package installation

src/apt-packages/devcontainer-feature.json, src/r-packages/devcontainer-feature.json
=> [apt-packages][r-packages] Add `proposals` to all `string` type options

src/r-apt/NOTES.md, src/r-apt/devcontainer-feature.json, src/r-apt/install.sh, test/r-apt/bspm-debian.sh, test/r-apt/bspm-ubuntu.sh, test/r-apt/scenarios.json
Close #69
Add a new option to set up bspm.
=> [r-apt]: installBspm option

.github/workflows/release.yaml
Same as devcontainers/feature-starter#64
=> ci: fix bot's config of git

src/rstudio-server/NOTES.md, src/rstudio-server/devcontainer-feature.json, src/rstudio-server/install.sh
=> fix(rstudio-server): supports ubuntu noble
