src/quarto/devcontainer-feature.json

https://containers.dev/implementors/features/#devcontainer-feature-json-properties
It appears that the installation of vscode extensions can be defined here.

Add vscode setting to quarto-cli feature

---

src/r-rig/devcontainer-feature.json
src/r-rig/install.sh

R installed with rig has `PKG_SYSREQS="true"` set in `/opt/R/*/lib/R/library/base/R/Rprofile` by default.
This is often useful as it means that system libraries are installed automatically when possible by `pak::pak`, but the user must edit the Rprofile to turn this off.
I found that this setting installing older versions of pandoc on Ubuntu, so I will change this.
This PR also includes other minor refactoring.

[r-rig] Do not set `PKG_SYSREQS="true"` in the Rprofile

---

src/r-rig/install.sh
test/r-rig/scenarios.json
test/r-rig/version-latest.sh

In r-rig, version is passed directly to rig as an argument and `latest` is not a valid value, but it is common for other devcontainer features to allow the version to be specified as `latest`.
Therefore, allow `latest` version for compatibility.

[r-lig] Allow `latest` for version of R

---

src/r-rig/NOTES.md
src/r-rig/devcontainer-feature.json
src/r-rig/install.sh
test/r-rig/install-on-rocker-r-ver.sh
test/r-rig/rpackages-source-install.sh
test/r-rig/scenarios.json

Allows this feature to be used to install R packages on R installed images.
ToDo

[r-lig] Skip install rig but install R packages, when R is already installed

---

src/r-rig/NOTES.md
src/r-rig/devcontainer-feature.json
src/r-rig/install.sh
test/_global/r_quarto.sh
test/_global/scenarios.json
test/r-rig/rpackages-source-install.sh
test/r-rig/scenarios.json

close #18, close #35, close #46
With this update, the packages installed on the following Dockerfile can be installed by this feature.
https://github.com/microsoft/vscode-dev-containers/blob/1d482aca6136a2d24c46e32ad645df54109143ac/containers/r/.devcontainer/Dockerfile
Note: This update is to make this feature also available for use in installing these packages in `rocker/r-ver`, etc.
So I am switching `pak` to the nightly version (0.3.1.9000 or later) that has not yet been released. (See r-lib/pak#251)

[r-rig] Options to install devtools, jupyterlab, radian

---

src/quarto-cli/devcontainer-feature.json
src/quarto-cli/install.sh
src/r-rig/devcontainer-feature.json
src/r-rig/install.sh

close #57
Set these to the `installAfter` properties because they have dependencies on the creation of a non-root user by `common-utils` or on Python 3 installed by `python`.

[quarto-cli][r-rig] Add `installAfter` settings

---

src/quarto-cli/devcontainer-feature.json
src/r-rig/devcontainer-feature.json
test/quarto-cli/scenarios.json

Close #62
Since [the current published features](https://containers.dev/features) are basically version 1.0, I would like to bump the version numbers to 1.0 in line with other features before these are in wide use.

[quarto-cli][r-rig] v1.0.0 Release

---

.github/workflows/test.yaml
README.md
src/pandoc/NOTES.md
src/pandoc/devcontainer-feature.json
src/pandoc/install.sh
test/_global/r-apt_pandoc.sh
test/_global/scenarios.json
test/pandoc/scenarios.json
test/pandoc/test.sh
test/pandoc/version-specific.sh

`r-apt` have no option to install the latest Pandoc unlike `r-rig`, so adds a separated feature to install latest Pandoc.
(This feature is a partial cutout of `r-rig`)

New feature: pandoc

---

src/r-apt/README.md
src/r-apt/devcontainer-feature.json

If the version option is not used, there seems to be no problem with deleting it. (c.f. `ghcr.io/devcontainers/features/common-utils`)

[r-apt] Remove unused version option

---

src/quarto-cli/NOTES.md
src/r-rig/NOTES.md

[Docs] Remove `remoteUser` from examples

---

src/r-rig/devcontainer-feature.json
src/r-rig/install.sh

Addresses rocker-org/devcontainer-images#39
It appears that the `~/.gitconfig` file is generated when the `credentials` package is source installed. (r-lib/credentials#25)
Until this can be circumvented, the generated `.gitconfig` file should be removed.

[r-rig] This feature should not add a `.gitconfig` file to the user's home

---

src/miniforge/devcontainer-feature.json
src/miniforge/install.sh

It has been downloaded 2,000 times and seems to be stable enough, so bump to version 1.0.0.

[miniforge] Bump to v1.0.0

---

test/r-rig/python-packages-global.sh

In #63, I added a test to check the path of radian when radian is installed on an image with a non-root user, but the user in the test has switched from root to non-root user, so I need to update the test to check the path.

[r-rig] Minor fix of test (check radian's path)

---

src/r-rig/devcontainer-feature.json
src/r-rig/install.sh
test/r-rig/install-on-devcontainer-r-ver.sh
test/r-rig/scenarios.json

Copied the `pakVersion` option from #120.
If we are installing R packages with this Feature on an R-installed image, `pak` may already be installed.
The default is to skip `pak` installation if `pak` is already installed.

[r-rig] Add a new option to choose pak version to be installed

---

src/renv-cache/devcontainer-feature.json
src/renv-cache/install.sh

When I used this Feature in my VS Code Dev Containers, the cache directory was owned by root and the cache directory could not be used unless the ownership was manually changed.
Local test with an R package project
```json
{
"name": "R (rocker/r-ver base)",
"image": "ghcr.io/rocker-org/devcontainer/r-ver:4",
"features": {
"./renv-cache": {}
},
"postCreateCommand": "R -q -e 'renv::install()'"
}
```

[renv-cache] Create cache dir in the image to fix permission error

---

.devcontainer.json
src/miniforge/devcontainer-feature.json
src/miniforge/install.sh
test/miniforge/mambaforge-existing-conda.sh
test/miniforge/scenarios.json

Fixes #166 
Note that this does not handle the case where the existing version is not the version requested. I started to address it, but it is made more complicated by the fact that mambaforge versions don't seem to keep up with official conda releases, so I didn't venture further down that path (i.e. if someone comes with an image with a fresh conda install, we would almost certainly be down-grading it here, which might not be desired).
I also updated the devcontainer spec of this repo because it was using an outdated `docker-from-docker` feature, which in turn made the tests in the tests break when running in the devcontainer.

[miniforge] no fail on existing installation

---

src/rstudio-server/NOTES.md
src/rstudio-server/devcontainer-feature.json
src/rstudio-server/oncreate.sh
test/rstudio-server/scenarios.json
test/rstudio-server/update-prefs.sh
test/rstudio-server/update-prefs/Dockerfile

Add the ability to update `initial_working_directory` of `rstudio-prefs.json` using the `jq` command if `rstudio-prefs.json` already exists.

[rstudio-server] support for updating already existing prefs.json

---

src/rstudio-server/devcontainer-feature.json
src/rstudio-server/install.sh
test/rstudio-server/scenarios.json

Considering that this Feature is used to change the configuration of an image that already has RStudio Server installed, I think the default should be `false`.

[rstudio-server] change the `allowReinstall` option's default value to `false`

---

.devcontainer.json
README.md

Update the outdated container definition as in https://github.com/devcontainers/feature-starter and make minor modifications to the README.

chore: Update devcontainer.json and README

---

src/quarto-cli/NOTES.md
src/quarto-cli/install.sh
test/quarto-cli/chromium-on-ubuntu.sh
test/quarto-cli/scenarios.json

The package list came from <https://pptr.dev/next/troubleshooting#running-puppeteer-on-wsl-windows-subsystem-for-linux>

[quarto-cli] chromium deps test on ubuntu

---

src/r-apt/NOTES.md
src/r-apt/devcontainer-feature.json
src/r-apt/install.sh

This PR also tweaks installation on Debian. (Related to https://github.com/rocker-org/devcontainer-features/issues/173#issuecomment-1677169159)

[r-apt]: If R is already installed the installation should fail

---

src/r-packages/devcontainer-feature.json
src/r-packages/install.sh
test/apt-packages/install-curl-nano-wget-ws.sh
test/apt-packages/scenarios.json
test/r-packages/install-cli-rlang-ws.sh
test/r-packages/scenarios.json

This is a small change to allow for whitespace in the `packages` specification, so that using
```jsonc
"packages": "cli, rlang"
```
does not lead to an error.

[r-packages] allow whitespace in `packages`

---

src/renv-cache/devcontainer-feature.json
src/renv-cache/install.sh
src/renv-cache/poststart.sh
test/renv-cache/gh-version-renv.sh
test/renv-cache/r-apt.sh
test/renv-cache/r-rig.sh
test/renv-cache/rocker-r-ver.sh
test/renv-cache/test.sh

Closes #209 
Updates the ownership of the `$RENV_PATHS_CACHE` directory such that when `updateRemoteUserUID` is set, the ownership of the cache is the same as the workspace. The test cases have also been updated to check the permissions of the directory.

Update ownership of `$RENV_PATHS_CACHE` to correct uid on `postStartCommand`

---

src/r-apt/devcontainer-feature.json
src/r-apt/install.sh
src/r-packages/devcontainer-feature.json
src/r-packages/install.sh
src/r-rig/devcontainer-feature.json
src/r-rig/install.sh

`pak` has been released frequently over the past few years, and I believe the stable version is now sufficient for our needs.

[r-apt][r-packages][r-rig]: install stable version of pak by default (instead of devel version)

---

test/_global/r-apt_pandoc.sh
test/miniforge/mambaforge-pypy3.sh
test/miniforge/miniforge-pypy3.sh
test/miniforge/miniforge3.sh
test/miniforge/test.sh
test/pandoc/test.sh
test/r-rig/latest-pandoc.sh

Currently the devcontainer CLI may not use the root user during testing, so these codes need to be removed.

test: remove outdated tests and fix pandoc's version regex

---

src/apt-packages/NOTES.md
src/r-apt/NOTES.md

Considering R users who may used to installing R packages via `install.packages(...)` (where package names may be a mix of upper- and lower-case letters) from an R session, I believe it may be useful to document that installing R packages via `apt-packages` requires that the package name be lowercase within `r-cran-<package>`.

docs(r-apt): Added case-sensitivity of apt packages warning

---

src/r-apt/devcontainer-feature.json
src/r-apt/install.sh
test/r-apt/scenarios.json

feat!(r-apt): support arm64 platform
